// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: provlabs/vault/v1/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the set of module parameters.
type Params struct {
	// tech_fee_address is the address where all AUM fees are collected and which holds
	// the authority to update per-vault bips.
	TechFeeAddress string `protobuf:"bytes,1,opt,name=tech_fee_address,json=techFeeAddress,proto3" json:"tech_fee_address,omitempty"`
	// default_aum_fee_bips is the default fee rate (in basis points) applied to new vaults upon creation.
	DefaultAumFeeBips uint32 `protobuf:"varint,2,opt,name=default_aum_fee_bips,json=defaultAumFeeBips,proto3" json:"default_aum_fee_bips,omitempty"`
	// max_vault_nav_entries caps how many internal NAV entries a vault may add. Total vault
	// value iterates this table on every valuation, so bounding it keeps the per-block
	// valuation cost predictable. Genesis import preserves entries beyond the cap and only
	// logs, so imported state may exceed it. A value of 0 means the module default applies.
	MaxVaultNavEntries uint32 `protobuf:"varint,3,opt,name=max_vault_nav_entries,json=maxVaultNavEntries,proto3" json:"max_vault_nav_entries,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_023bfbd86d9377d5, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetTechFeeAddress() string {
	if m != nil {
		return m.TechFeeAddress
	}
	return ""
}

func (m *Params) GetDefaultAumFeeBips() uint32 {
	if m != nil {
		return m.DefaultAumFeeBips
	}
	return 0
}

func (m *Params) GetMaxVaultNavEntries() uint32 {
	if m != nil {
		return m.MaxVaultNavEntries
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "provlabs.vault.v1.Params")
}

func init() { proto.RegisterFile("provlabs/vault/v1/params.proto", fileDescriptor_023bfbd86d9377d5) }

var fileDescriptor_023bfbd86d9377d5 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2b, 0x28, 0xca, 0x2f,
	0xcb, 0x49, 0x4c, 0x2a, 0xd6, 0x2f, 0x4b, 0x2c, 0xcd, 0x29, 0xd1, 0x2f, 0x33, 0xd4, 0x2f, 0x48,
	0x2c, 0x4a, 0xcc, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0x84, 0xc9, 0xeb, 0x81,
	0xe5, 0xf5, 0xca, 0x0c, 0xa5, 0x24, 0x93, 0xf3, 0x8b, 0x73, 0xf3, 0x8b, 0xe3, 0xc1, 0x0a, 0xf4,
	0x21, 0x1c, 0x88, 0x6a, 0x29, 0x91, 0xf4, 0xfc, 0xf4, 0x7c, 0x88, 0x38, 0x88, 0x05, 0x11, 0x55,
	0xda, 0xc6, 0xc8, 0xc5, 0x16, 0x00, 0x36, 0x54, 0xc8, 0x89, 0x4b, 0xa0, 0x24, 0x35, 0x39, 0x23,
	0x3e, 0x2d, 0x35, 0x35, 0x3e, 0x31, 0x25, 0xa5, 0x28, 0xb5, 0xb8, 0x58, 0x82, 0x51, 0x81, 0x51,
	0x83, 0xd3, 0x49, 0xe2, 0xd2, 0x16, 0x5d, 0x11, 0xa8, 0x61, 0x8e, 0x10, 0x99, 0xe0, 0x92, 0xa2,
	0xcc, 0xbc, 0xf4, 0x20, 0x3e, 0x90, 0x0e, 0xb7, 0xd4, 0x54, 0xa8, 0xa8, 0x90, 0x3e, 0x97, 0x48,
	0x4a, 0x6a, 0x1a, 0xc8, 0x35, 0xf1, 0x89, 0xa5, 0xb9, 0x60, 0xa3, 0x92, 0x32, 0x0b, 0x8a, 0x25,
	0x98, 0x14, 0x18, 0x35, 0x78, 0x83, 0x04, 0xa1, 0x72, 0x8e, 0xa5, 0xb9, 0x6e, 0xa9, 0xa9, 0x4e,
	0x99, 0x05, 0xc5, 0x42, 0x86, 0x5c, 0xa2, 0xb9, 0x89, 0x15, 0xf1, 0x60, 0x0f, 0xc4, 0xe7, 0x25,
	0x96, 0xc5, 0xa7, 0xe6, 0x95, 0x14, 0x65, 0xa6, 0x16, 0x4b, 0x30, 0x83, 0x75, 0x08, 0xe5, 0x26,
	0x56, 0x84, 0x81, 0xe4, 0xfc, 0x12, 0xcb, 0x5c, 0x21, 0x32, 0x56, 0x2c, 0x2f, 0x16, 0xc8, 0x33,
	0x3a, 0x59, 0x9e, 0x78, 0x24, 0xc7, 0x78, 0xe1, 0x91, 0x1c, 0xe3, 0x83, 0x47, 0x72, 0x8c, 0x13,
	0x1e, 0xcb, 0x31, 0x5c, 0x78, 0x2c, 0xc7, 0x70, 0xe3, 0xb1, 0x1c, 0x43, 0x94, 0x7c, 0x7a, 0x66,
	0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0x3e, 0x5a, 0x08, 0x96, 0x54, 0x16, 0xa4, 0x16,
	0x27, 0xb1, 0x81, 0xbd, 0x6e, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xc0, 0x87, 0xb5, 0xfb, 0x60,
	0x01, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TechFeeAddress != that1.TechFeeAddress {
		return false
	}
	if this.DefaultAumFeeBips != that1.DefaultAumFeeBips {
		return false
	}
	if this.MaxVaultNavEntries != that1.MaxVaultNavEntries {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.MaxVaultNavEntries != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxVaultNavEntries))
		i--
		dAtA[i] = 0x18
	}
	if m.DefaultAumFeeBips != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DefaultAumFeeBips))
		i--
		dAtA[i] = 0x10
	}
	if len(m.TechFeeAddress) > 0 {
		i -= len(m.TechFeeAddress)
		copy(dAtA[i:], m.TechFeeAddress)
		i = encodeVarintParams(dAtA, i, uint64(len(m.TechFeeAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TechFeeAddress)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.DefaultAumFeeBips != 0 {
		n += 1 + sovParams(uint64(m.DefaultAumFeeBips))
	}
	if m.MaxVaultNavEntries != 0 {
		n += 1 + sovParams(uint64(m.MaxVaultNavEntries))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TechFeeAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TechFeeAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DefaultAumFeeBips", wireType)
			}
			m.DefaultAumFeeBips = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DefaultAumFeeBips |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxVaultNavEntries", wireType)
			}
			m.MaxVaultNavEntries = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxVaultNavEntries |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
