// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: provlabs/vault/v1/vault.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types1 "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/x/auth/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// VaultAccount represents a central holding place for assets, governed by a set of rules.
// It is based on the ERC-4626 standard and builds upon the Provenance Marker module.
type VaultAccount struct {
	// base_account cosmos account information including address and coin holdings.
	*types.BaseAccount `protobuf:"bytes,1,opt,name=base_account,json=baseAccount,proto3,embedded=base_account" json:"base_account,omitempty"`
	// total_shares is the total number of shares that have ever been issued by the vault.
	// It serves as the canonical supply-of-record for all shares, regardless of whether
	// they are held locally on Provenance or externally (e.g., bridged).
	TotalShares types1.Coin `protobuf:"bytes,2,opt,name=total_shares,json=totalShares,proto3" json:"total_shares"`
	// underlying_asset is the vault’s single principal collateral AND valuation/base unit.
	// - Exactly one denom.
	// - Total Vault Value (TVV) and NAV-per-share are computed and reported in this denom.
	// - Interest accrual, fees, and internal accounting are measured in this denom.
	// - Held assets acquired via settlement must have an internal NAV record priced INTO this denom.
	UnderlyingAsset string `protobuf:"bytes,3,opt,name=underlying_asset,json=underlyingAsset,proto3" json:"underlying_asset,omitempty"`
	// payment_denom always equals underlying_asset. Vaults are single-denom; the
	// field is inert and retained only for wire compatibility.
	//
	// Deprecated: The mixed-denom vault concept has been flattened into a single
	// underlying denom. Deletion of this field is deferred to a future major release.
	PaymentDenom string `protobuf:"bytes,4,opt,name=payment_denom,json=paymentDenom,proto3" json:"payment_denom,omitempty"` // Deprecated: Do not use.
	// admin is the address that has administrative privileges over the vault.
	Admin string `protobuf:"bytes,5,opt,name=admin,proto3" json:"admin,omitempty"`
	// current_interest_rate is a decimal string (e.g., "0.9" for 90% and "0.9001353" for 90.01353%) representing the actual annual interest rate currently being applied.
	// This may be adjusted programmatically (e.g., due to lack of funds).
	CurrentInterestRate string `protobuf:"bytes,6,opt,name=current_interest_rate,json=currentInterestRate,proto3" json:"current_interest_rate,omitempty"`
	// desired_interest_rate is a decimal string (e.g., "0.9" for 90% and "0.9001353" for 90.01353%) representing the target annual interest rate that the vault intends to apply.
	DesiredInterestRate string `protobuf:"bytes,7,opt,name=desired_interest_rate,json=desiredInterestRate,proto3" json:"desired_interest_rate,omitempty"`
	// min_interest_rate is a decimal string (e.g., "0.9" for 90% and "0.9001353" for 90.01353%) representing the lowest annual interest rate the admin is allowed to set.
	// If unset (empty string), there is no lower limit.
	MinInterestRate string `protobuf:"bytes,8,opt,name=min_interest_rate,json=minInterestRate,proto3" json:"min_interest_rate,omitempty"`
	// max_interest_rate is a decimal string (e.g., "0.9" for 90% and "0.9001353" for 90.01353%) representing the highest annual interest rate the admin is allowed to set.
	// If unset (empty string), there is no upper limit.
	MaxInterestRate string `protobuf:"bytes,9,opt,name=max_interest_rate,json=maxInterestRate,proto3" json:"max_interest_rate,omitempty"`
	// The start time (in Unix seconds) of the current interest accrual period.
	PeriodStart int64 `protobuf:"varint,10,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	// The expire time (in Unix seconds) of the current interest accrual period.
	PeriodTimeout int64 `protobuf:"varint,11,opt,name=period_timeout,json=periodTimeout,proto3" json:"period_timeout,omitempty"`
	// swap_in_enabled indicates whether users are allowed to deposit into the vault.
	SwapInEnabled bool `protobuf:"varint,12,opt,name=swap_in_enabled,json=swapInEnabled,proto3" json:"swap_in_enabled,omitempty"`
	// swap_out_enabled indicates whether users are allowed to withdraw from the vault.
	SwapOutEnabled bool `protobuf:"varint,13,opt,name=swap_out_enabled,json=swapOutEnabled,proto3" json:"swap_out_enabled,omitempty"`
	// withdrawal_delay_seconds is the configured time period (in seconds) that a withdrawal
	// request must wait in the pending queue before being processed.
	WithdrawalDelaySeconds uint64 `protobuf:"varint,14,opt,name=withdrawal_delay_seconds,json=withdrawalDelaySeconds,proto3" json:"withdrawal_delay_seconds,omitempty"`
	// paused indicates that all user-facing swap-in and swap-out operations are disabled.
	Paused bool `protobuf:"varint,15,opt,name=paused,proto3" json:"paused,omitempty"`
	// paused_balance is the total vault value snapshot taken at the moment of pausing.
	// This value is used for all NAV calculations while the vault is paused to prevent
	// apparent devaluation during collateral rebalancing. It is cleared upon unpausing.
	// Nothing done during the pause moves it, neither a principal deposit or withdrawal
	// nor a NAV repricing; those all take effect together when the vault is unpaused.
	PausedBalance types1.Coin `protobuf:"bytes,16,opt,name=paused_balance,json=pausedBalance,proto3" json:"paused_balance"`
	// paused_reason is a human-readable string explaining why the vault was paused, particularly for automatic pauses.
	PausedReason string `protobuf:"bytes,17,opt,name=paused_reason,json=pausedReason,proto3" json:"paused_reason,omitempty"`
	// paused_by is the address that initiated the current pause, empty for an automatic
	// pause and cleared on unpause. MsgRepriceVault consults it so the NAV authority
	// can only resume a pause it took itself.
	PausedBy string `protobuf:"bytes,30,opt,name=paused_by,json=pausedBy,proto3" json:"paused_by,omitempty"`
	// paused_forced reports whether the current pause waived the strict reconcile and
	// valuation gate, true for a forced MsgPauseVault and every automatic pause. A forced
	// pause records a tolerated failure, so MsgRepriceVault refuses to resume one.
	PausedForced bool `protobuf:"varint,31,opt,name=paused_forced,json=pausedForced,proto3" json:"paused_forced,omitempty"`
	// bridge_address is the single external address allowed to mint or burn shares on behalf
	// of this vault (e.g., for bridging to another chain). All mint/burn must flow through the
	// vault keeper, which enforces that marker supply never exceeds total_shares.
	BridgeAddress string `protobuf:"bytes,18,opt,name=bridge_address,json=bridgeAddress,proto3" json:"bridge_address,omitempty"`
	// bridge_enabled indicates whether the bridge functionality is active. If false, the
	// bridge_address has no effect and cannot mint or burn.
	BridgeEnabled bool `protobuf:"varint,19,opt,name=bridge_enabled,json=bridgeEnabled,proto3" json:"bridge_enabled,omitempty"`
	// asset_manager is an optional address that, when set, is authorized to manage certain
	// collateral operations alongside the admin (e.g., pausing/unpausing, depositing/withdrawing
	// principal or interest funds). If unset (empty string), only the admin may perform those actions.
	AssetManager string `protobuf:"bytes,20,opt,name=asset_manager,json=assetManager,proto3" json:"asset_manager,omitempty"`
	// fee_period_start is the start time (in Unix seconds) of the current AUM fee collection period.
	// This is a module-managed timestamp kept in sync with the fee timeout queue machinery.
	FeePeriodStart int64 `protobuf:"varint,21,opt,name=fee_period_start,json=feePeriodStart,proto3" json:"fee_period_start,omitempty"`
	// fee_period_timeout is the end time (in Unix seconds) of the current AUM fee collection period.
	// This is a module-managed timestamp kept in sync with the fee timeout queue machinery.
	FeePeriodTimeout int64 `protobuf:"varint,22,opt,name=fee_period_timeout,json=feePeriodTimeout,proto3" json:"fee_period_timeout,omitempty"`
	// outstanding_aum_fee is the amount of AUM fee that has been calculated but not yet collected
	// due to insufficient liquidity in the principal marker. This amount is always denominated
	// in the vault's underlying_asset, must be preserved, and is carried into valuation computations.
	OutstandingAumFee types1.Coin `protobuf:"bytes,23,opt,name=outstanding_aum_fee,json=outstandingAumFee,proto3" json:"outstanding_aum_fee"`
	// aum_fee_bips is the AUM fee rate (in basis points) for this specific vault.
	// Units: Basis Points (1 bps = 0.01%).
	// Valid Range: 0 to 10000 (0% to 100%).
	// A value of 0 disables AUM fee collection for this vault.
	// Negative values are not supported (uint32).
	AumFeeBips uint32 `protobuf:"varint,24,opt,name=aum_fee_bips,json=aumFeeBips,proto3" json:"aum_fee_bips,omitempty"`
	// min_swap_in_value is a string representing the minimum value required for a deposit.
	// - The value is measured in the underlying_asset.
	// - Values must be non-negative (>= 0).
	// - If empty ("") or "0", there is no minimum limit.
	MinSwapInValue string `protobuf:"bytes,25,opt,name=min_swap_in_value,json=minSwapInValue,proto3" json:"min_swap_in_value,omitempty"`
	// min_swap_out_value is a string representing the minimum value required for a withdrawal.
	// - The value is measured in the underlying_asset.
	// - Outgoing redemptions are converted to this unit before checking.
	// - Values must be non-negative (>= 0).
	// - If empty ("") or "0", there is no minimum limit.
	MinSwapOutValue string `protobuf:"bytes,26,opt,name=min_swap_out_value,json=minSwapOutValue,proto3" json:"min_swap_out_value,omitempty"`
	// max_swap_in_value is a string representing the maximum value allowed for a deposit.
	// - The value is measured in the underlying_asset.
	// - Values must be positive (> 0).
	// - An empty string "" indicates no maximum limit.
	MaxSwapInValue string `protobuf:"bytes,27,opt,name=max_swap_in_value,json=maxSwapInValue,proto3" json:"max_swap_in_value,omitempty"`
	// max_swap_out_value is a string representing the maximum value allowed for a withdrawal.
	// - The value is measured in the underlying_asset.
	// - Outgoing redemptions are converted to this unit before checking.
	// - Values must be positive (> 0).
	// - An empty string "" indicates no maximum limit.
	MaxSwapOutValue string `protobuf:"bytes,28,opt,name=max_swap_out_value,json=maxSwapOutValue,proto3" json:"max_swap_out_value,omitempty"`
	// nav_authority is the address authorized to mutate this vault's internal NAV
	// table via MsgUpdateVaultNAV. If empty, the vault admin is treated as the NAV
	// authority. It is rotated only via MsgUpdateNAVAuthority.
	NavAuthority string `protobuf:"bytes,29,opt,name=nav_authority,json=navAuthority,proto3" json:"nav_authority,omitempty"`
}

func (m *VaultAccount) Reset()         { *m = VaultAccount{} }
func (m *VaultAccount) String() string { return proto.CompactTextString(m) }
func (*VaultAccount) ProtoMessage()    {}
func (*VaultAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e0d78aae3177bea, []int{0}
}
func (m *VaultAccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VaultAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VaultAccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VaultAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VaultAccount.Merge(m, src)
}
func (m *VaultAccount) XXX_Size() int {
	return m.Size()
}
func (m *VaultAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_VaultAccount.DiscardUnknown(m)
}

var xxx_messageInfo_VaultAccount proto.InternalMessageInfo

func (m *VaultAccount) GetTotalShares() types1.Coin {
	if m != nil {
		return m.TotalShares
	}
	return types1.Coin{}
}

func (m *VaultAccount) GetUnderlyingAsset() string {
	if m != nil {
		return m.UnderlyingAsset
	}
	return ""
}

// Deprecated: Do not use.
func (m *VaultAccount) GetPaymentDenom() string {
	if m != nil {
		return m.PaymentDenom
	}
	return ""
}

func (m *VaultAccount) GetAdmin() string {
	if m != nil {
		return m.Admin
	}
	return ""
}

func (m *VaultAccount) GetCurrentInterestRate() string {
	if m != nil {
		return m.CurrentInterestRate
	}
	return ""
}

func (m *VaultAccount) GetDesiredInterestRate() string {
	if m != nil {
		return m.DesiredInterestRate
	}
	return ""
}

func (m *VaultAccount) GetMinInterestRate() string {
	if m != nil {
		return m.MinInterestRate
	}
	return ""
}

func (m *VaultAccount) GetMaxInterestRate() string {
	if m != nil {
		return m.MaxInterestRate
	}
	return ""
}

func (m *VaultAccount) GetPeriodStart() int64 {
	if m != nil {
		return m.PeriodStart
	}
	return 0
}

func (m *VaultAccount) GetPeriodTimeout() int64 {
	if m != nil {
		return m.PeriodTimeout
	}
	return 0
}

func (m *VaultAccount) GetSwapInEnabled() bool {
	if m != nil {
		return m.SwapInEnabled
	}
	return false
}

func (m *VaultAccount) GetSwapOutEnabled() bool {
	if m != nil {
		return m.SwapOutEnabled
	}
	return false
}

func (m *VaultAccount) GetWithdrawalDelaySeconds() uint64 {
	if m != nil {
		return m.WithdrawalDelaySeconds
	}
	return 0
}

func (m *VaultAccount) GetPaused() bool {
	if m != nil {
		return m.Paused
	}
	return false
}

func (m *VaultAccount) GetPausedBalance() types1.Coin {
	if m != nil {
		return m.PausedBalance
	}
	return types1.Coin{}
}

func (m *VaultAccount) GetPausedReason() string {
	if m != nil {
		return m.PausedReason
	}
	return ""
}

func (m *VaultAccount) GetPausedBy() string {
	if m != nil {
		return m.PausedBy
	}
	return ""
}

func (m *VaultAccount) GetPausedForced() bool {
	if m != nil {
		return m.PausedForced
	}
	return false
}

func (m *VaultAccount) GetBridgeAddress() string {
	if m != nil {
		return m.BridgeAddress
	}
	return ""
}

func (m *VaultAccount) GetBridgeEnabled() bool {
	if m != nil {
		return m.BridgeEnabled
	}
	return false
}

func (m *VaultAccount) GetAssetManager() string {
	if m != nil {
		return m.AssetManager
	}
	return ""
}

func (m *VaultAccount) GetFeePeriodStart() int64 {
	if m != nil {
		return m.FeePeriodStart
	}
	return 0
}

func (m *VaultAccount) GetFeePeriodTimeout() int64 {
	if m != nil {
		return m.FeePeriodTimeout
	}
	return 0
}

func (m *VaultAccount) GetOutstandingAumFee() types1.Coin {
	if m != nil {
		return m.OutstandingAumFee
	}
	return types1.Coin{}
}

func (m *VaultAccount) GetAumFeeBips() uint32 {
	if m != nil {
		return m.AumFeeBips
	}
	return 0
}

func (m *VaultAccount) GetMinSwapInValue() string {
	if m != nil {
		return m.MinSwapInValue
	}
	return ""
}

func (m *VaultAccount) GetMinSwapOutValue() string {
	if m != nil {
		return m.MinSwapOutValue
	}
	return ""
}

func (m *VaultAccount) GetMaxSwapInValue() string {
	if m != nil {
		return m.MaxSwapInValue
	}
	return ""
}

func (m *VaultAccount) GetMaxSwapOutValue() string {
	if m != nil {
		return m.MaxSwapOutValue
	}
	return ""
}

func (m *VaultAccount) GetNavAuthority() string {
	if m != nil {
		return m.NavAuthority
	}
	return ""
}

// VaultNAV is a single internal net asset value entry recording the price of one
// asset denom held by a vault. The vault module is the sole source of truth for
// these values; the NAV authority maintains them via MsgUpdateVaultNAV.
type VaultNAV struct {
	// denom is the asset denomination this entry prices.
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	// price is the total value of `volume` units of the denom, denominated in the
	// vault's underlying asset. The per-unit value is price divided by volume.
	Price types1.Coin `protobuf:"bytes,2,opt,name=price,proto3" json:"price"`
	// volume is the number of units of the denom that price covers. It must be
	// positive; the per-unit value of the denom is price divided by volume.
	Volume cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=volume,proto3,customtype=cosmossdk.io/math.Int" json:"volume"`
	// source identifies the origin of this NAV entry (for example an oracle name
	// or the settlement path), mirroring the Marker module's NAV source attribution.
	Source string `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	// updated_block_height is the block height at which this entry was last updated.
	UpdatedBlockHeight int64 `protobuf:"varint,5,opt,name=updated_block_height,json=updatedBlockHeight,proto3" json:"updated_block_height,omitempty"`
	// updated_time is the block time at which this entry was last updated.
	UpdatedTime time.Time `protobuf:"bytes,6,opt,name=updated_time,json=updatedTime,proto3,stdtime" json:"updated_time"`
}

func (m *VaultNAV) Reset()         { *m = VaultNAV{} }
func (m *VaultNAV) String() string { return proto.CompactTextString(m) }
func (*VaultNAV) ProtoMessage()    {}
func (*VaultNAV) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e0d78aae3177bea, []int{1}
}
func (m *VaultNAV) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *VaultNAV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_VaultNAV.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *VaultNAV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VaultNAV.Merge(m, src)
}
func (m *VaultNAV) XXX_Size() int {
	return m.Size()
}
func (m *VaultNAV) XXX_DiscardUnknown() {
	xxx_messageInfo_VaultNAV.DiscardUnknown(m)
}

var xxx_messageInfo_VaultNAV proto.InternalMessageInfo

func (m *VaultNAV) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func (m *VaultNAV) GetPrice() types1.Coin {
	if m != nil {
		return m.Price
	}
	return types1.Coin{}
}

func (m *VaultNAV) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *VaultNAV) GetUpdatedBlockHeight() int64 {
	if m != nil {
		return m.UpdatedBlockHeight
	}
	return 0
}

func (m *VaultNAV) GetUpdatedTime() time.Time {
	if m != nil {
		return m.UpdatedTime
	}
	return time.Time{}
}

// AccountBalance represents the coin balance of a single account.
type AccountBalance struct {
	// address is the account address.
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	// coins is the balance of the account.
	Coins github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=coins,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"coins"`
}

func (m *AccountBalance) Reset()         { *m = AccountBalance{} }
func (m *AccountBalance) String() string { return proto.CompactTextString(m) }
func (*AccountBalance) ProtoMessage()    {}
func (*AccountBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e0d78aae3177bea, []int{2}
}
func (m *AccountBalance) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AccountBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AccountBalance.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AccountBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountBalance.Merge(m, src)
}
func (m *AccountBalance) XXX_Size() int {
	return m.Size()
}
func (m *AccountBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountBalance.DiscardUnknown(m)
}

var xxx_messageInfo_AccountBalance proto.InternalMessageInfo

// PendingSwapOut are swap outs that have not yet been processed and completed.
type PendingSwapOut struct {
	// owner is the address initiating the swap out.
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	// vault_address is the address of the vault processing the withdrawal.
	VaultAddress string `protobuf:"bytes,2,opt,name=vault_address,json=vaultAddress,proto3" json:"vault_address,omitempty"`
	// shares are the shares that were escrowed by the user.
	Shares types1.Coin `protobuf:"bytes,3,opt,name=shares,proto3" json:"shares"`
	// redeem_denom is the denomination of the asset to be redeemed. Always the
	// vault's underlying_asset; retained for wire compatibility.
	RedeemDenom string `protobuf:"bytes,4,opt,name=redeem_denom,json=redeemDenom,proto3" json:"redeem_denom,omitempty"` // Deprecated: Do not use.
	// failure_count is the number of consecutive failed processing attempts that
	// left this request queued. Each failure re-keys the request to a later retry
	// time so it cannot hold the front of the queue. Reset when expedited.
	FailureCount uint32 `protobuf:"varint,5,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
}

func (m *PendingSwapOut) Reset()         { *m = PendingSwapOut{} }
func (m *PendingSwapOut) String() string { return proto.CompactTextString(m) }
func (*PendingSwapOut) ProtoMessage()    {}
func (*PendingSwapOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e0d78aae3177bea, []int{3}
}
func (m *PendingSwapOut) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PendingSwapOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PendingSwapOut.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PendingSwapOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingSwapOut.Merge(m, src)
}
func (m *PendingSwapOut) XXX_Size() int {
	return m.Size()
}
func (m *PendingSwapOut) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingSwapOut.DiscardUnknown(m)
}

var xxx_messageInfo_PendingSwapOut proto.InternalMessageInfo

func (m *PendingSwapOut) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *PendingSwapOut) GetVaultAddress() string {
	if m != nil {
		return m.VaultAddress
	}
	return ""
}

func (m *PendingSwapOut) GetShares() types1.Coin {
	if m != nil {
		return m.Shares
	}
	return types1.Coin{}
}

// Deprecated: Do not use.
func (m *PendingSwapOut) GetRedeemDenom() string {
	if m != nil {
		return m.RedeemDenom
	}
	return ""
}

func (m *PendingSwapOut) GetFailureCount() uint32 {
	if m != nil {
		return m.FailureCount
	}
	return 0
}

// Payment is the vault module's view of a Provenance exchange-module payment. It
// mirrors the exchange Payment, exposing only the fields relevant to the vault's
// asset settlement workflow.
//
// It serves two roles. As a query result it reports a pending payment targeting the
// vault. In MsgAcceptAssetRequest it carries the terms the asset manager reviewed, and
// settlement proceeds only if they still match the stored payment exactly.
type Payment struct {
	// source is the account that created the payment and owns the escrowed source_amount.
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// source_amount is the funds the source pays the target. A hold is placed on this
	// amount in the source account until the payment is accepted, rejected, or cancelled.
	SourceAmount github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=source_amount,json=sourceAmount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"source_amount"`
	// target is the account that can accept the payment; for the vault's settlement
	// workflow it is the vault.
	Target string `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	// target_amount is the funds the target pays the source in exchange for source_amount.
	TargetAmount github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,4,rep,name=target_amount,json=targetAmount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"target_amount"`
	// external_id, together with source, uniquely identifies the payment.
	ExternalId string `protobuf:"bytes,5,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
}

func (m *Payment) Reset()         { *m = Payment{} }
func (m *Payment) String() string { return proto.CompactTextString(m) }
func (*Payment) ProtoMessage()    {}
func (*Payment) Descriptor() ([]byte, []int) {
	return fileDescriptor_2e0d78aae3177bea, []int{4}
}
func (m *Payment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Payment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Payment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Payment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payment.Merge(m, src)
}
func (m *Payment) XXX_Size() int {
	return m.Size()
}
func (m *Payment) XXX_DiscardUnknown() {
	xxx_messageInfo_Payment.DiscardUnknown(m)
}

var xxx_messageInfo_Payment proto.InternalMessageInfo

func (m *Payment) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Payment) GetSourceAmount() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.SourceAmount
	}
	return nil
}

func (m *Payment) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *Payment) GetTargetAmount() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.TargetAmount
	}
	return nil
}

func (m *Payment) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

func init() {
	proto.RegisterType((*VaultAccount)(nil), "provlabs.vault.v1.VaultAccount")
	proto.RegisterType((*VaultNAV)(nil), "provlabs.vault.v1.VaultNAV")
	proto.RegisterType((*AccountBalance)(nil), "provlabs.vault.v1.AccountBalance")
	proto.RegisterType((*PendingSwapOut)(nil), "provlabs.vault.v1.PendingSwapOut")
	proto.RegisterType((*Payment)(nil), "provlabs.vault.v1.Payment")
}

func init() { proto.RegisterFile("provlabs/vault/v1/vault.proto", fileDescriptor_2e0d78aae3177bea) }

var fileDescriptor_2e0d78aae3177bea = []byte{
	// 1272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xbd, 0x8f, 0x13, 0x47,
	0x14, 0xbf, 0xbd, 0x2f, 0x8e, 0xf1, 0xda, 0x77, 0x37, 0x1c, 0x64, 0x20, 0xc1, 0x76, 0x0e, 0x91,
	0x38, 0x4a, 0xce, 0xe6, 0x88, 0x50, 0x3e, 0x24, 0x44, 0x6c, 0x08, 0xe1, 0x8a, 0x04, 0xb4, 0x87,
	0x28, 0xd2, 0xac, 0xc6, 0xbb, 0xef, 0xec, 0x15, 0xbb, 0x33, 0xab, 0x99, 0x59, 0xdf, 0xb9, 0x4f,
	0x91, 0x92, 0x2e, 0x2d, 0x6d, 0xd2, 0xa4, 0xe1, 0x8f, 0xa0, 0x44, 0x54, 0x51, 0x0a, 0x88, 0xa0,
	0x49, 0x9d, 0xbf, 0x20, 0x9a, 0x8f, 0xf5, 0x7d, 0x20, 0xd9, 0xd7, 0x50, 0x79, 0xe6, 0xf7, 0x7e,
	0xef, 0xf7, 0x9e, 0x77, 0xde, 0xcc, 0x7b, 0xe8, 0x72, 0x2e, 0xf8, 0x28, 0xa5, 0x7d, 0xd9, 0x19,
	0xd1, 0x22, 0x55, 0x9d, 0xd1, 0xb6, 0x5d, 0xb4, 0x73, 0xc1, 0x15, 0xc7, 0xeb, 0xa5, 0xb9, 0x6d,
	0xd1, 0xd1, 0xf6, 0xa5, 0x7a, 0xc4, 0x65, 0xc6, 0x65, 0x87, 0x16, 0x6a, 0xd8, 0x19, 0x6d, 0xf7,
	0x41, 0xd1, 0x6d, 0xb3, 0xb1, 0x2e, 0x13, 0x7b, 0x9f, 0x4a, 0x98, 0xd8, 0x23, 0x9e, 0x30, 0x67,
	0xbf, 0x68, 0xed, 0xa1, 0xd9, 0x75, 0xec, 0xc6, 0x99, 0x36, 0x06, 0x7c, 0xc0, 0x2d, 0xae, 0x57,
	0x0e, 0x6d, 0x0c, 0x38, 0x1f, 0xa4, 0xd0, 0x31, 0xbb, 0x7e, 0xb1, 0xd7, 0x51, 0x49, 0x06, 0x52,
	0xd1, 0x2c, 0xb7, 0x84, 0xcd, 0xdf, 0xab, 0xc8, 0x7f, 0xa4, 0xd3, 0xeb, 0x46, 0x11, 0x2f, 0x98,
	0xc2, 0x3b, 0xc8, 0xd7, 0xd1, 0x43, 0x6a, 0xf7, 0xc4, 0x6b, 0x7a, 0xad, 0xca, 0xf5, 0x66, 0xdb,
	0x05, 0x33, 0xc9, 0xba, 0xcc, 0xda, 0x3d, 0x2a, 0xc1, 0xf9, 0xf5, 0x16, 0x5f, 0xbc, 0x6a, 0x78,
	0x41, 0xa5, 0x7f, 0x08, 0xe1, 0x1e, 0xf2, 0x15, 0x57, 0x34, 0x0d, 0xe5, 0x90, 0x0a, 0x90, 0x64,
	0xde, 0x48, 0x5d, 0x2c, 0xa5, 0x34, 0x75, 0x22, 0x75, 0x9b, 0x27, 0xac, 0xb7, 0xf8, 0xfc, 0x55,
	0x63, 0x2e, 0xa8, 0x18, 0xa7, 0x5d, 0xe3, 0x83, 0x3f, 0x43, 0x6b, 0x05, 0x8b, 0x41, 0xa4, 0xe3,
	0x84, 0x0d, 0x42, 0x2a, 0x25, 0x28, 0xb2, 0xd0, 0xf4, 0x5a, 0x67, 0x83, 0xd5, 0x43, 0xbc, 0xab,
	0x61, 0xfc, 0x29, 0xaa, 0xe6, 0x74, 0x9c, 0x01, 0x53, 0x61, 0x0c, 0x8c, 0x67, 0x64, 0x51, 0xf3,
	0x7a, 0xf3, 0xc4, 0x0b, 0x7c, 0x67, 0xb8, 0xa3, 0x71, 0xdc, 0x46, 0x4b, 0x34, 0xce, 0x12, 0x46,
	0x96, 0x0c, 0x81, 0xbc, 0x7c, 0xb6, 0xb5, 0xe1, 0x72, 0xea, 0xc6, 0xb1, 0x00, 0x29, 0x77, 0x95,
	0x48, 0xd8, 0x20, 0xb0, 0x34, 0x7c, 0x0f, 0x9d, 0x8f, 0x0a, 0x21, 0xb4, 0x70, 0xc2, 0x14, 0x08,
	0x90, 0x2a, 0x14, 0x54, 0x01, 0x59, 0x36, 0xfe, 0x1b, 0x2f, 0x9f, 0x6d, 0xad, 0x39, 0xff, 0x3b,
	0x10, 0x39, 0xdf, 0x73, 0xce, 0x65, 0xc7, 0x79, 0x04, 0x54, 0x81, 0x56, 0x8a, 0x41, 0x26, 0x02,
	0xe2, 0x13, 0x4a, 0x67, 0xa6, 0x29, 0x39, 0x97, 0x63, 0x4a, 0xdf, 0xa1, 0xf5, 0x2c, 0x61, 0x27,
	0x54, 0x56, 0xa6, 0xa8, 0xac, 0x66, 0x09, 0x7b, 0x47, 0x81, 0x1e, 0x9c, 0x50, 0x38, 0x3b, 0x55,
	0x81, 0x1e, 0x1c, 0x53, 0xf8, 0x18, 0xf9, 0x39, 0x88, 0x84, 0xc7, 0xa1, 0x54, 0x54, 0x28, 0x82,
	0x9a, 0x5e, 0x6b, 0x21, 0xa8, 0x58, 0x6c, 0x57, 0x43, 0xf8, 0x2a, 0xaa, 0x39, 0x8a, 0x2e, 0x3c,
	0x5e, 0x28, 0x52, 0x31, 0xa4, 0xaa, 0x45, 0x1f, 0x5a, 0x10, 0x7f, 0x82, 0x56, 0xe5, 0x3e, 0xcd,
	0xc3, 0x84, 0x85, 0xc0, 0x68, 0x3f, 0x85, 0x98, 0xf8, 0x4d, 0xaf, 0xb5, 0x12, 0x54, 0x35, 0xbc,
	0xc3, 0xbe, 0xb7, 0x20, 0x6e, 0xa1, 0x35, 0xc3, 0xe3, 0x85, 0x9a, 0x10, 0xab, 0x86, 0x58, 0xd3,
	0xf8, 0xfd, 0x42, 0x95, 0xcc, 0xaf, 0x11, 0xd9, 0x4f, 0xd4, 0x30, 0x16, 0x74, 0x9f, 0xa6, 0x61,
	0x0c, 0x29, 0x1d, 0x87, 0x12, 0x22, 0xce, 0x62, 0x49, 0x6a, 0x4d, 0xaf, 0xb5, 0x18, 0x5c, 0x38,
	0xb4, 0xdf, 0xd1, 0xe6, 0x5d, 0x6b, 0xc5, 0x17, 0xd0, 0x72, 0x4e, 0x0b, 0x09, 0x31, 0x59, 0x35,
	0xca, 0x6e, 0x87, 0xef, 0xa2, 0x9a, 0x5d, 0x85, 0x7d, 0x9a, 0x52, 0x16, 0x01, 0x59, 0x3b, 0x5d,
	0x3d, 0x57, 0xad, 0x5b, 0xcf, 0x7a, 0xe1, 0x2b, 0xc8, 0x01, 0xa1, 0x00, 0x2a, 0x39, 0x23, 0xeb,
	0xa6, 0x9c, 0x7d, 0x0b, 0x06, 0x06, 0xc3, 0x37, 0xd0, 0xd9, 0x32, 0xd8, 0x98, 0xd4, 0x67, 0x94,
	0xe9, 0x8a, 0x0b, 0x30, 0x3e, 0xa2, 0xbd, 0xc7, 0x45, 0x04, 0x31, 0x69, 0x98, 0xbf, 0xe0, 0xb4,
	0xef, 0x1a, 0x0c, 0xdf, 0x42, 0xb5, 0xbe, 0x48, 0xe2, 0x01, 0x84, 0xd4, 0xca, 0x10, 0x3c, 0x23,
	0x40, 0xd5, 0xf2, 0x1d, 0xa8, 0x0f, 0xd5, 0x09, 0x94, 0x67, 0x70, 0xce, 0x1e, 0x96, 0x45, 0xcb,
	0x23, 0xb8, 0x89, 0xaa, 0xe6, 0xbe, 0x86, 0x19, 0x65, 0x74, 0x00, 0x82, 0x6c, 0xcc, 0x08, 0xe3,
	0x1b, 0xfa, 0x8f, 0x96, 0xad, 0xcf, 0x7a, 0x0f, 0x20, 0x3c, 0x56, 0x61, 0xe7, 0x4d, 0xf1, 0xd4,
	0xf6, 0x00, 0x1e, 0x1c, 0x29, 0xb2, 0x2f, 0x10, 0x3e, 0xc2, 0x2c, 0x0b, 0xed, 0x82, 0xe1, 0xae,
	0x4d, 0xb8, 0x65, 0xad, 0xdd, 0x47, 0xe7, 0x78, 0xa1, 0xa4, 0xa2, 0x2c, 0x36, 0x4f, 0x4a, 0x91,
	0x85, 0x7b, 0x00, 0xe4, 0x83, 0xd3, 0x1d, 0xe6, 0xfa, 0x11, 0xdf, 0x6e, 0x91, 0xdd, 0x05, 0xc0,
	0x4d, 0xe4, 0x3b, 0x91, 0xb0, 0x9f, 0xe4, 0x92, 0x90, 0xa6, 0xd7, 0xaa, 0x06, 0x88, 0x1a, 0x6b,
	0x2f, 0xc9, 0x25, 0xbe, 0x65, 0x2f, 0x6b, 0x59, 0xe2, 0x23, 0x9a, 0x16, 0x40, 0x2e, 0xbe, 0x73,
	0xd5, 0x76, 0x98, 0x72, 0x5f, 0xa2, 0x96, 0x25, 0x6c, 0xd7, 0x54, 0xfe, 0x23, 0xcd, 0xc5, 0x5d,
	0x84, 0x27, 0x02, 0xba, 0xf6, 0xad, 0xc2, 0xa5, 0x29, 0x0a, 0xab, 0x4e, 0xe1, 0x7e, 0xa1, 0xac,
	0xc4, 0x2d, 0x7b, 0xdd, 0x8f, 0xe7, 0xf0, 0xe1, 0xd4, 0x1c, 0xe8, 0xc1, 0xc9, 0x1c, 0x4a, 0x81,
	0xc3, 0x1c, 0x3e, 0x9a, 0x9a, 0x83, 0x55, 0x98, 0xe4, 0x70, 0x13, 0x55, 0x19, 0x1d, 0x85, 0xba,
	0x87, 0x70, 0x91, 0xa8, 0x31, 0xb9, 0x3c, 0xab, 0x22, 0x18, 0x1d, 0x75, 0x4b, 0xf6, 0xe6, 0x9f,
	0xf3, 0x68, 0xc5, 0xf4, 0xaa, 0x9f, 0xba, 0x8f, 0xf0, 0x06, 0x5a, 0xb2, 0xaf, 0xbc, 0x67, 0xae,
	0x8f, 0xdd, 0xe0, 0x1b, 0x68, 0x29, 0x17, 0x49, 0x04, 0xa7, 0xed, 0x35, 0x96, 0x8d, 0x6f, 0xa3,
	0xe5, 0x11, 0x4f, 0x8b, 0x0c, 0x6c, 0x6f, 0xe9, 0x7d, 0xae, 0x8d, 0x7f, 0xbf, 0x6a, 0x9c, 0xb7,
	0xee, 0x32, 0x7e, 0xdc, 0x4e, 0x78, 0x27, 0xa3, 0x6a, 0xa8, 0xff, 0xde, 0xcb, 0x67, 0x5b, 0xe8,
	0xf0, 0xcf, 0x06, 0xce, 0x55, 0x3f, 0x1c, 0x92, 0x17, 0x22, 0x02, 0xdb, 0x78, 0x02, 0xb7, 0xc3,
	0xd7, 0xd0, 0x46, 0x91, 0xc7, 0x54, 0xe9, 0xcb, 0x9c, 0xf2, 0xe8, 0x71, 0x38, 0x84, 0x64, 0x30,
	0x54, 0xa6, 0xfb, 0x2c, 0x04, 0xd8, 0xd9, 0x7a, 0xda, 0x74, 0xcf, 0x58, 0xf0, 0x0f, 0xc8, 0x2f,
	0x3d, 0x74, 0x35, 0x9b, 0x3e, 0x53, 0xb9, 0x7e, 0xa9, 0x6d, 0x9b, 0x79, 0xbb, 0x6c, 0xe6, 0xed,
	0x87, 0x65, 0x33, 0xef, 0xad, 0xe8, 0x84, 0x9f, 0xbc, 0xd6, 0x1d, 0xd8, 0x79, 0x6a, 0xdb, 0xe6,
	0x6f, 0x1e, 0xaa, 0x95, 0x0d, 0xda, 0x3d, 0x3f, 0x04, 0x9d, 0x29, 0xaf, 0xbd, 0xfd, 0x72, 0xe5,
	0x16, 0x53, 0xb4, 0xa4, 0x47, 0x0d, 0xdd, 0xa7, 0x17, 0xa6, 0x7f, 0xbb, 0x6b, 0x3a, 0xda, 0x1f,
	0xaf, 0x1b, 0xad, 0x41, 0xa2, 0x86, 0x45, 0xbf, 0x1d, 0xf1, 0xcc, 0x0d, 0x23, 0xee, 0x67, 0x4b,
	0xc6, 0x8f, 0x3b, 0x6a, 0x9c, 0x83, 0x34, 0x0e, 0x32, 0xb0, 0xca, 0xdf, 0xae, 0xfc, 0xfa, 0xb4,
	0x31, 0xf7, 0xef, 0xd3, 0xc6, 0xdc, 0xe6, 0x2f, 0xf3, 0xa8, 0xf6, 0x00, 0xcc, 0x35, 0x72, 0x25,
	0xa2, 0xdb, 0x32, 0xdf, 0x67, 0x20, 0x6c, 0x5e, 0xd3, 0xda, 0xb2, 0xa1, 0xe9, 0x6a, 0x32, 0x83,
	0xd5, 0xe4, 0x19, 0x9b, 0x9f, 0x55, 0x4d, 0x86, 0x5e, 0xbe, 0x62, 0x5f, 0xa1, 0x65, 0x37, 0x97,
	0x2c, 0x9c, 0xae, 0x56, 0x1c, 0x1d, 0x5f, 0x45, 0xbe, 0x80, 0x18, 0x20, 0x7b, 0x67, 0xcc, 0xa8,
	0x58, 0xdc, 0x4e, 0x19, 0x57, 0x50, 0x75, 0x8f, 0x26, 0x69, 0x21, 0x20, 0xb4, 0x93, 0xd4, 0x92,
	0x79, 0x17, 0x7c, 0x07, 0xde, 0xd6, 0xd8, 0xe6, 0x7f, 0xf3, 0xe8, 0xcc, 0x03, 0x3b, 0x9b, 0xe0,
	0x6b, 0x93, 0xfa, 0x99, 0xf5, 0x01, 0xca, 0xca, 0xca, 0x51, 0xd5, 0xae, 0x42, 0x9a, 0x99, 0x10,
	0xef, 0xe1, 0xe4, 0x7c, 0x1b, 0xa1, 0x6b, 0x02, 0xe8, 0x1c, 0x15, 0x15, 0x83, 0x72, 0x08, 0x9b,
	0x96, 0xa3, 0xe5, 0xe9, 0x1c, 0xed, 0xaa, 0xcc, 0x71, 0xf1, 0x3d, 0xe4, 0x68, 0x23, 0xb8, 0x1c,
	0x1b, 0xa8, 0x02, 0x07, 0x0a, 0x04, 0xa3, 0x69, 0x98, 0xc4, 0x76, 0xc8, 0x0b, 0x50, 0x09, 0xed,
	0xc4, 0xbd, 0x6f, 0x9e, 0xbf, 0xa9, 0x7b, 0x2f, 0xde, 0xd4, 0xbd, 0x7f, 0xde, 0xd4, 0xbd, 0x27,
	0x6f, 0xeb, 0x73, 0x2f, 0xde, 0xd6, 0xe7, 0xfe, 0x7a, 0x5b, 0x9f, 0xfb, 0xb9, 0x71, 0x24, 0xe4,
	0x89, 0xe1, 0xde, 0xc4, 0xeb, 0x2f, 0x9b, 0xbb, 0xf7, 0xe5, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x7d, 0xb9, 0xa9, 0x4f, 0xfb, 0x0b, 0x00, 0x00,
}

func (m *VaultAccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VaultAccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VaultAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PausedForced {
		i--
		if m.PausedForced {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xf8
	}
	if len(m.PausedBy) > 0 {
		i -= len(m.PausedBy)
		copy(dAtA[i:], m.PausedBy)
		i = encodeVarintVault(dAtA, i, uint64(len(m.PausedBy)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xf2
	}
	if len(m.NavAuthority) > 0 {
		i -= len(m.NavAuthority)
		copy(dAtA[i:], m.NavAuthority)
		i = encodeVarintVault(dAtA, i, uint64(len(m.NavAuthority)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xea
	}
	if len(m.MaxSwapOutValue) > 0 {
		i -= len(m.MaxSwapOutValue)
		copy(dAtA[i:], m.MaxSwapOutValue)
		i = encodeVarintVault(dAtA, i, uint64(len(m.MaxSwapOutValue)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xe2
	}
	if len(m.MaxSwapInValue) > 0 {
		i -= len(m.MaxSwapInValue)
		copy(dAtA[i:], m.MaxSwapInValue)
		i = encodeVarintVault(dAtA, i, uint64(len(m.MaxSwapInValue)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xda
	}
	if len(m.MinSwapOutValue) > 0 {
		i -= len(m.MinSwapOutValue)
		copy(dAtA[i:], m.MinSwapOutValue)
		i = encodeVarintVault(dAtA, i, uint64(len(m.MinSwapOutValue)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xd2
	}
	if len(m.MinSwapInValue) > 0 {
		i -= len(m.MinSwapInValue)
		copy(dAtA[i:], m.MinSwapInValue)
		i = encodeVarintVault(dAtA, i, uint64(len(m.MinSwapInValue)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xca
	}
	if m.AumFeeBips != 0 {
		i = encodeVarintVault(dAtA, i, uint64(m.AumFeeBips))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xc0
	}
	{
		size, err := m.OutstandingAumFee.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintVault(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0xba
	if m.FeePeriodTimeout != 0 {
		i = encodeVarintVault(dAtA, i, uint64(m.FeePeriodTimeout))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb0
	}
	if m.FeePeriodStart != 0 {
		i = encodeVarintVault(dAtA, i, uint64(m.FeePeriodStart))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa8
	}
	if len(m.AssetManager) > 0 {
		i -= len(m.AssetManager)
		copy(dAtA[i:], m.AssetManager)
		i = encodeVarintVault(dAtA, i, uint64(len(m.AssetManager)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa2
	}
	if m.BridgeEnabled {
		i--
		if m.BridgeEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x98
	}
	if len(m.BridgeAddress) > 0 {
		i -= len(m.BridgeAddress)
		copy(dAtA[i:], m.BridgeAddress)
		i = encodeVarintVault(dAtA, i, uint64(len(m.BridgeAddress)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x92
	}
	if len(m.PausedReason) > 0 {
		i -= len(m.PausedReason)
		copy(dAtA[i:], m.PausedReason)
		i = encodeVarintVault(dAtA, i, uint64(len(m.PausedReason)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x8a
	}
	{
		size, err := m.PausedBalance.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintVault(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1
	i--
	dAtA[i] = 0x82
	if m.Paused {
		i--
		if m.Paused {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x78
	}
	if m.WithdrawalDelaySeconds != 0 {
		i = encodeVarintVault(dAtA, i, uint64(m.WithdrawalDelaySeconds))
		i--
		dAtA[i] = 0x70
	}
	if m.SwapOutEnabled {
		i--
		if m.SwapOutEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x68
	}
	if m.SwapInEnabled {
		i--
		if m.SwapInEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x60
	}
	if m.PeriodTimeout != 0 {
		i = encodeVarintVault(dAtA, i, uint64(m.PeriodTimeout))
		i--
		dAtA[i] = 0x58
	}
	if m.PeriodStart != 0 {
		i = encodeVarintVault(dAtA, i, uint64(m.PeriodStart))
		i--
		dAtA[i] = 0x50
	}
	if len(m.MaxInterestRate) > 0 {
		i -= len(m.MaxInterestRate)
		copy(dAtA[i:], m.MaxInterestRate)
		i = encodeVarintVault(dAtA, i, uint64(len(m.MaxInterestRate)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.MinInterestRate) > 0 {
		i -= len(m.MinInterestRate)
		copy(dAtA[i:], m.MinInterestRate)
		i = encodeVarintVault(dAtA, i, uint64(len(m.MinInterestRate)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.DesiredInterestRate) > 0 {
		i -= len(m.DesiredInterestRate)
		copy(dAtA[i:], m.DesiredInterestRate)
		i = encodeVarintVault(dAtA, i, uint64(len(m.DesiredInterestRate)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.CurrentInterestRate) > 0 {
		i -= len(m.CurrentInterestRate)
		copy(dAtA[i:], m.CurrentInterestRate)
		i = encodeVarintVault(dAtA, i, uint64(len(m.CurrentInterestRate)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Admin) > 0 {
		i -= len(m.Admin)
		copy(dAtA[i:], m.Admin)
		i = encodeVarintVault(dAtA, i, uint64(len(m.Admin)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.PaymentDenom) > 0 {
		i -= len(m.PaymentDenom)
		copy(dAtA[i:], m.PaymentDenom)
		i = encodeVarintVault(dAtA, i, uint64(len(m.PaymentDenom)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.UnderlyingAsset) > 0 {
		i -= len(m.UnderlyingAsset)
		copy(dAtA[i:], m.UnderlyingAsset)
		i = encodeVarintVault(dAtA, i, uint64(len(m.UnderlyingAsset)))
		i--
		dAtA[i] = 0x1a
	}
	{
		size, err := m.TotalShares.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintVault(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.BaseAccount != nil {
		{
			size, err := m.BaseAccount.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintVault(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *VaultNAV) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *VaultNAV) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *VaultNAV) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n5, err5 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.UpdatedTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.UpdatedTime):])
	if err5 != nil {
		return 0, err5
	}
	i -= n5
	i = encodeVarintVault(dAtA, i, uint64(n5))
	i--
	dAtA[i] = 0x32
	if m.UpdatedBlockHeight != 0 {
		i = encodeVarintVault(dAtA, i, uint64(m.UpdatedBlockHeight))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Source) > 0 {
		i -= len(m.Source)
		copy(dAtA[i:], m.Source)
		i = encodeVarintVault(dAtA, i, uint64(len(m.Source)))
		i--
		dAtA[i] = 0x22
	}
	{
		size := m.Volume.Size()
		i -= size
		if _, err := m.Volume.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintVault(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Price.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintVault(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintVault(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *AccountBalance) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AccountBalance) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AccountBalance) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Coins) > 0 {
		for iNdEx := len(m.Coins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Coins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintVault(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintVault(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PendingSwapOut) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PendingSwapOut) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PendingSwapOut) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.FailureCount != 0 {
		i = encodeVarintVault(dAtA, i, uint64(m.FailureCount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.RedeemDenom) > 0 {
		i -= len(m.RedeemDenom)
		copy(dAtA[i:], m.RedeemDenom)
		i = encodeVarintVault(dAtA, i, uint64(len(m.RedeemDenom)))
		i--
		dAtA[i] = 0x22
	}
	{
		size, err := m.Shares.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintVault(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.VaultAddress) > 0 {
		i -= len(m.VaultAddress)
		copy(dAtA[i:], m.VaultAddress)
		i = encodeVarintVault(dAtA, i, uint64(len(m.VaultAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintVault(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Payment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Payment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Payment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ExternalId) > 0 {
		i -= len(m.ExternalId)
		copy(dAtA[i:], m.ExternalId)
		i = encodeVarintVault(dAtA, i, uint64(len(m.ExternalId)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.TargetAmount) > 0 {
		for iNdEx := len(m.TargetAmount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TargetAmount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintVault(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Target) > 0 {
		i -= len(m.Target)
		copy(dAtA[i:], m.Target)
		i = encodeVarintVault(dAtA, i, uint64(len(m.Target)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SourceAmount) > 0 {
		for iNdEx := len(m.SourceAmount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SourceAmount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintVault(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Source) > 0 {
		i -= len(m.Source)
		copy(dAtA[i:], m.Source)
		i = encodeVarintVault(dAtA, i, uint64(len(m.Source)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintVault(dAtA []byte, offset int, v uint64) int {
	offset -= sovVault(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *VaultAccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BaseAccount != nil {
		l = m.BaseAccount.Size()
		n += 1 + l + sovVault(uint64(l))
	}
	l = m.TotalShares.Size()
	n += 1 + l + sovVault(uint64(l))
	l = len(m.UnderlyingAsset)
	if l > 0 {
		n += 1 + l + sovVault(uint64(l))
	}
	l = len(m.PaymentDenom)
	if l > 0 {
		n += 1 + l + sovVault(uint64(l))
	}
	l = len(m.Admin)
	if l > 0 {
		n += 1 + l + sovVault(uint64(l))
	}
	l = len(m.CurrentInterestRate)
	if l > 0 {
		n += 1 + l + sovVault(uint64(l))
	}
	l = len(m.DesiredInterestRate)
	if l > 0 {
		n += 1 + l + sovVault(uint64(l))
	}
	l = len(m.MinInterestRate)
	if l > 0 {
		n += 1 + l + sovVault(uint64(l))
	}
	l = len(m.MaxInterestRate)
	if l > 0 {
		n += 1 + l + sovVault(uint64(l))
	}
	if m.PeriodStart != 0 {
		n += 1 + sovVault(uint64(m.PeriodStart))
	}
	if m.PeriodTimeout != 0 {
		n += 1 + sovVault(uint64(m.PeriodTimeout))
	}
	if m.SwapInEnabled {
		n += 2
	}
	if m.SwapOutEnabled {
		n += 2
	}
	if m.WithdrawalDelaySeconds != 0 {
		n += 1 + sovVault(uint64(m.WithdrawalDelaySeconds))
	}
	if m.Paused {
		n += 2
	}
	l = m.PausedBalance.Size()
	n += 2 + l + sovVault(uint64(l))
	l = len(m.PausedReason)
	if l > 0 {
		n += 2 + l + sovVault(uint64(l))
	}
	l = len(m.BridgeAddress)
	if l > 0 {
		n += 2 + l + sovVault(uint64(l))
	}
	if m.BridgeEnabled {
		n += 3
	}
	l = len(m.AssetManager)
	if l > 0 {
		n += 2 + l + sovVault(uint64(l))
	}
	if m.FeePeriodStart != 0 {
		n += 2 + sovVault(uint64(m.FeePeriodStart))
	}
	if m.FeePeriodTimeout != 0 {
		n += 2 + sovVault(uint64(m.FeePeriodTimeout))
	}
	l = m.OutstandingAumFee.Size()
	n += 2 + l + sovVault(uint64(l))
	if m.AumFeeBips != 0 {
		n += 2 + sovVault(uint64(m.AumFeeBips))
	}
	l = len(m.MinSwapInValue)
	if l > 0 {
		n += 2 + l + sovVault(uint64(l))
	}
	l = len(m.MinSwapOutValue)
	if l > 0 {
		n += 2 + l + sovVault(uint64(l))
	}
	l = len(m.MaxSwapInValue)
	if l > 0 {
		n += 2 + l + sovVault(uint64(l))
	}
	l = len(m.MaxSwapOutValue)
	if l > 0 {
		n += 2 + l + sovVault(uint64(l))
	}
	l = len(m.NavAuthority)
	if l > 0 {
		n += 2 + l + sovVault(uint64(l))
	}
	l = len(m.PausedBy)
	if l > 0 {
		n += 2 + l + sovVault(uint64(l))
	}
	if m.PausedForced {
		n += 3
	}
	return n
}

func (m *VaultNAV) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovVault(uint64(l))
	}
	l = m.Price.Size()
	n += 1 + l + sovVault(uint64(l))
	l = m.Volume.Size()
	n += 1 + l + sovVault(uint64(l))
	l = len(m.Source)
	if l > 0 {
		n += 1 + l + sovVault(uint64(l))
	}
	if m.UpdatedBlockHeight != 0 {
		n += 1 + sovVault(uint64(m.UpdatedBlockHeight))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.UpdatedTime)
	n += 1 + l + sovVault(uint64(l))
	return n
}

func (m *AccountBalance) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovVault(uint64(l))
	}
	if len(m.Coins) > 0 {
		for _, e := range m.Coins {
			l = e.Size()
			n += 1 + l + sovVault(uint64(l))
		}
	}
	return n
}

func (m *PendingSwapOut) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovVault(uint64(l))
	}
	l = len(m.VaultAddress)
	if l > 0 {
		n += 1 + l + sovVault(uint64(l))
	}
	l = m.Shares.Size()
	n += 1 + l + sovVault(uint64(l))
	l = len(m.RedeemDenom)
	if l > 0 {
		n += 1 + l + sovVault(uint64(l))
	}
	if m.FailureCount != 0 {
		n += 1 + sovVault(uint64(m.FailureCount))
	}
	return n
}

func (m *Payment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Source)
	if l > 0 {
		n += 1 + l + sovVault(uint64(l))
	}
	if len(m.SourceAmount) > 0 {
		for _, e := range m.SourceAmount {
			l = e.Size()
			n += 1 + l + sovVault(uint64(l))
		}
	}
	l = len(m.Target)
	if l > 0 {
		n += 1 + l + sovVault(uint64(l))
	}
	if len(m.TargetAmount) > 0 {
		for _, e := range m.TargetAmount {
			l = e.Size()
			n += 1 + l + sovVault(uint64(l))
		}
	}
	l = len(m.ExternalId)
	if l > 0 {
		n += 1 + l + sovVault(uint64(l))
	}
	return n
}

func sovVault(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozVault(x uint64) (n int) {
	return sovVault(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *VaultAccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVault
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VaultAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VaultAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseAccount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BaseAccount == nil {
				m.BaseAccount = &types.BaseAccount{}
			}
			if err := m.BaseAccount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalShares", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalShares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnderlyingAsset", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UnderlyingAsset = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaymentDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PaymentDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Admin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Admin = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentInterestRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CurrentInterestRate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DesiredInterestRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DesiredInterestRate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinInterestRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinInterestRate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxInterestRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxInterestRate = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeriodStart", wireType)
			}
			m.PeriodStart = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PeriodStart |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeriodTimeout", wireType)
			}
			m.PeriodTimeout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PeriodTimeout |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapInEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SwapInEnabled = bool(v != 0)
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapOutEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SwapOutEnabled = bool(v != 0)
		case 14:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WithdrawalDelaySeconds", wireType)
			}
			m.WithdrawalDelaySeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WithdrawalDelaySeconds |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 15:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Paused", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Paused = bool(v != 0)
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PausedBalance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PausedBalance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PausedReason", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PausedReason = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BridgeAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BridgeAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 19:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BridgeEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.BridgeEnabled = bool(v != 0)
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AssetManager", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AssetManager = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 21:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeePeriodStart", wireType)
			}
			m.FeePeriodStart = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FeePeriodStart |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 22:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeePeriodTimeout", wireType)
			}
			m.FeePeriodTimeout = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FeePeriodTimeout |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 23:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutstandingAumFee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OutstandingAumFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 24:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AumFeeBips", wireType)
			}
			m.AumFeeBips = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AumFeeBips |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 25:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinSwapInValue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinSwapInValue = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 26:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinSwapOutValue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MinSwapOutValue = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 27:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSwapInValue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxSwapInValue = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 28:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxSwapOutValue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MaxSwapOutValue = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 29:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NavAuthority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NavAuthority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 30:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PausedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PausedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 31:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PausedForced", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.PausedForced = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipVault(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVault
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *VaultNAV) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVault
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: VaultNAV: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: VaultNAV: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Volume", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Volume.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Source = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedBlockHeight", wireType)
			}
			m.UpdatedBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.UpdatedTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVault(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVault
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AccountBalance) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVault
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AccountBalance: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AccountBalance: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Coins = append(m.Coins, types1.Coin{})
			if err := m.Coins[len(m.Coins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVault(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVault
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PendingSwapOut) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVault
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PendingSwapOut: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PendingSwapOut: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VaultAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VaultAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Shares", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Shares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RedeemDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RedeemDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FailureCount", wireType)
			}
			m.FailureCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FailureCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipVault(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVault
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Payment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowVault
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Payment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Payment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Source = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SourceAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SourceAmount = append(m.SourceAmount, types1.Coin{})
			if err := m.SourceAmount[len(m.SourceAmount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Target", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Target = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TargetAmount = append(m.TargetAmount, types1.Coin{})
			if err := m.TargetAmount[len(m.TargetAmount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExternalId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowVault
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthVault
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthVault
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExternalId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipVault(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthVault
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipVault(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowVault
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVault
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowVault
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthVault
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupVault
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthVault
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthVault        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowVault          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupVault = fmt.Errorf("proto: unexpected end of group")
)
